name: meme-search
channels:
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- py=1.4.34=py36hecf431b_1
- pytest=3.2.1=py36h9963153_1
- python=3.6.2=0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- whoosh=2.7.4=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - chardet==3.0.4
  - facebook-sdk==2.0.0
  - google==1.9.3
  - idna==2.6
  - olefile==0.44
  - pillow==4.3.0
  - pytesseract==0.1.7
  - requests==2.18.4
  - urllib3==1.22

